### PR TITLE
Add design-system-tokens repo

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

Last 2 commits are most relevant (those "beyond" usage of the script):
- 06f449b8830dde86537c8af48bd078884de08ef2
- 772ac34eb23e16e53c6235e9253102cf905ccfdc

## :link: External Links

https://app.asana.com/0/1201630204387510/1201901980035754/f

***

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by amyrlam** [comment]
Note: Manually moved https://github.com/hashicorp/design-system/issues/35 due to GitHub permissions issue, and archived https://github.com/hashicorp/design-system-tokens, LMK if you have any comment

**Review by didoo — APPROVED** [review]

**Review by Dhaulagiri — DISMISSED** [review]
I see some documentation updates, particularly around releasing, we could address in a separate PR, but one thing we _should_ do in this PR is run `yarn` from the monorepo root as I see some changes locally if I do that in this branch.

**Comment by amyrlam** [comment]
@Dhaulagiri made https://github.com/hashicorp/design-system/pull/34/commits/fb3ed39cd7005269e3be8bc854d1c7b1cbe3d826, FWIW will probably need another yarn.lock after merge

I can update the docs separately, here is a tick https://app.asana.com/0/1201630204387510/1201937957719919/f

**Comment by Dhaulagiri** [comment]
:shipit:

**Comment by amyrlam** [comment]
nm doesn't need a new `yarn.lock` post-merge (I thought it might cause there was a tricky rebase with the packages/tokens/yarn.lock, which seemed like NVA)

**Pull request merged**
