### PR TITLE
Showcase `.gts` - Initial setup

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

This PR does the initial setup of the `showcase` app, to be able to use the `.gts` file format for the `<Shw::***>` components.

### :hammer_and_wrench: Detailed description

In this PR I have:
- added necessary dev-dependencies:
    - `ember-template-imports`
    -  `prettier-plugin-ember-template-tag`
    - `@glint/environment-ember-template-imports`
- updated configuration files:
    - added overrides in `.template-lintrc.js` file to avoid [an issue with Prettier](https://github.com/ember-template-lint/ember-template-lint-plugin-prettier/issues/268) - taken from [this change](https://github.com/hashicorp/hds-plus/pull/8/files#diff-b002ff17d893f34646a0116dbf832e6a661053871eb2c737864ae72f5ed539e1) by @aklkv
    - updated the `showcase/.prettierrc.js file` per @aklkv [setup here](https://github.com/hashicorp/hds-plus/pull/1/commits/47b8905df61dee254b78e1784e63e619f135480d#diff-cd4dd089d1cdff928fc16e26f2a9d7748110e6afa47b241611e34414b31611d7)
    - added `ember-template-imports` to glint environment in `tsconfig.json`

### :link: External links

Jira ticket: https://hashicorp.atlassian.net/browse/HDS-3828

***

### 👀 Component checklist

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by aklkv — APPROVED** [review]
looks good, you  will need linter and prettier changes but for the purpose of getting gts actually working this will do just fine 👍🏻 

you might still needed after all https://github.com/hashicorp/design-system/actions/runs/10828172710/job/30042947081?pr=2412#step:7:16

**Comment by didoo** [comment]
Thanks @aklkv 🙏 for all the support in getting this PR and #2412 working

**Review by shleewhite — APPROVED** [review]

**Comment by shleewhite** [comment]
> CI seems happy, but I can't get it working locally, `yarn run lint:js` fails unexpectedly. @shleewhite have you encountered any issues?

@alex-ju nope... it it works for me - did you run `yarn install` first?
Screenshot 2024-09-13 at 9 13 36 AM

**Comment by alex-ju** [comment]
> > CI seems happy, but I can't get it working locally, `yarn run lint:js` fails unexpectedly. @shleewhite have you encountered any issues?
> 
> @alex-ju nope... it it works for me - did you run `yarn install` first? Screenshot 2024-09-13 at 9 13 36 AM

yep. don't mind me then, I'll find my way around – good to be merged!

**Pull request merged**
