### PR TITLE
Fix name in doc

### PR DESCRIPTION
**Pull request by amyrlam**
### :pushpin: Summary

Probably just a bad copypasta

- [n/a] TODO add changeset

***

### 👀 How to review

👉 Review commit-by-commit
👉 Review by files changed

Reviewer's checklist:

- [n/a] +1 Percy if applicable
- [n/a] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
> TODO add changeset

My $.02 is that an internal code comment shouldn't require a changeset

**Comment by Dhaulagiri** [comment]
> TODO add changeset

My $.02 is that an internal code comment shouldn't require a changeset

**Review by MelSumner — APPROVED** [review]
nice catch 👍

**Comment by amyrlam** [comment]
Sure no changeset SGTM... I was going to think about it today, because of all the discussions on SemVer yest. I'll go ahead and merge

**Comment by Dhaulagiri** [comment]
> I was going to think about it today, because of all the discussions on SemVer yest

strong nod. changesets has made me think about it _a lot_ more this week than I have in the past.

**Pull request merged**
