### PR TITLE
Updated export of icons from Figma

### PR DESCRIPTION
**Pull request by hashibot-hds**
### 📌 Summary
This PR adds Figma and Loom service icons.

### 🔗 External links
[HDS-768](https://hashicorp.atlassian.net/browse/HDS-768)
[HDS-767](https://hashicorp.atlassian.net/browse/HDS-767)

### CODE REVIEW

**Comment by cveigt** [comment]
@Dhaulagiri @didoo I'm getting quite a few errors this time. Could I get your help or guidance here?

**Comment by didoo** [comment]
> @Dhaulagiri @didoo I'm getting quite a few errors this time. Could I get your help or guidance here?

Fount the cause:
screenshot_2039

Now let me search for the root cause.

**Comment by didoo** [comment]
@cveigt @Dhaulagiri ok found the root cause: https://github.com/hashicorp/design-system/pull/689/commits/2a3cf57d67dde4c3a0c75f31234c4a1fb429aea5

now all the tests are passing in my local env, and I expect them to pass also here

**Review by didoo — APPROVED** [review]

**Comment by Dhaulagiri** [comment]
merging per discussion yesterday with @cveigt

**Pull request merged**
