### PR TITLE
"CopyButton" component - MVP

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

This is a "temporary" implementation of the `CopyButton` component (like an MVP) that will be used for the implementation of the `Dropdown` component (so we relieve @MelSumner to implement also this component, and focus on the `Dropdown` items (one of which may be a "copy item" that simply will consume the `CopyButton` as child. 

Preview of the documentation page: https://hds-components-git-copybutton-component-mvp-hashicorp.vercel.app/components/copy-button

🚨 **IMPORTANT**: at the moment we have only implemented the layout and the basic states (likely will be fine-tuned by @heatherlarsen in Figma) so that @MelSumner can use it in her code. We have **not** implemented any behaviour or interaction or extra functionality. In reality, in the products this component does much more than just copying to clipboard a string: it can be without container (just text and icon), it can have a success message or a tooltip, it can have different text between label and actual clipboard text, etc. We will work on these only later, because we will have to go through the standard process to unify all the different implementations (see links below): audit, design, CRD, code, etc.

**TODOs**
- [ ] support wrapping of the content ([example](https://www.figma.com/file/DUjKDINH2ps9ggk6YsAVC6/Dropdown?node-id=4653%3A18803))

### :camera_flash: Screenshots

How it will be used in the `Dropdown`:

screenshot_1114

### :link: External links
- [Cloud UI - Clipboard Copy Button](https://unofficial-design-system-search.vercel.app/?path=/story/cloud-ui-storybook_clipboardcopybutton--clipboard-copy-button)
- [Cloud UI - CopyCard](https://unofficial-design-system-search.vercel.app/?path=/story/cloud-ui-storybook_copycard--copy-card-with-clipboard-text)
- [Nomad - Copy Button](https://unofficial-design-system-search.vercel.app/?path=/story/nomad-storybook_components-copy-button--copy-button)
- [Consul - Copy Button](https://unofficial-design-system-search.vercel.app/?path=/story/consul-copy-button--consul-copy-button)

***

### 👀 How to review

👉 Review by files changed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by heatherlarsen** [comment]
@didoo a few notes...

- CopyButton should only allow a trailing icon
- Text and Icon are both required (so no icon only variant)
- There is no need for a disabled state
- The focus state doubles up the interior border color (it has a 1px border & an inset 1px box-shadow)
- The text doesn't appear to vertically align with the icon
- Is it possible to also support wrapping of the content ([example](https://www.figma.com/file/DUjKDINH2ps9ggk6YsAVC6/Dropdown?node-id=4653%3A18803))?

**Comment by didoo** [comment]
@heatherlarsen below my comments:

> CopyButton should only allow a trailing icon
> Text and Icon are both required (so no icon only variant)

See Consul: https://unofficial-design-system-search.vercel.app/?path=/story/consul-copy-button--consul-copy-button
Also, see Cloud UI: https://unofficial-design-system-search.vercel.app/?path=/story/cloud-ui-storybook_clipboardcopybutton--clipboard-copy-button

We have to understand if we want to unify both "entities" (the button and the box) since they're very similar, or no. For now, for the MVP, I would consider to support both under the same component, and later split it if needed.

> There is no need for a disabled state

OK, I've removed it.

> The focus state doubles up the interior border color (it has a 1px border & an inset 1px box-shadow)

Right! Fixed.

> The text doesn't appear to vertically align with the icon

Mmm, strange. It's aligned in the browser:
screenshot_1187
screenshot_1186

> Is it possible to also support wrapping of the content ([example](https://www.figma.com/file/DUjKDINH2ps9ggk6YsAVC6/Dropdown?node-id=4653%3A18803))?

Added a TODO in the PR description.

**Comment by heatherlarsen** [comment]
@didoo But these Consul use cases are different to what is being nested in the dropdown component (ie. they're not visible code snippets with a copy icon in the trailing position), so I don't think we should be basing how we build this on those examples. Even more so because we aren't officially supporting this yet and we haven't been able to do a full audit, which is likely to uncover many different use cases and variations for this type of component (code snippets, full code blocks, just a button with no visible example, etc).

Sorry if there was a miscommunication somewhere, but my intention wasn't for this to be built as it's own component yet. What we're doing in Figma is only to provide the bare minimum of support for this feature as it's used within the dropdown (so as to avoid a "Frankenstein" of nested components) and to only expose it as a part of the dropdown. It's a bandaid until we can officially build and support the individual component. Once it's prioritized and we can start working on it, we'll have a better understanding of all the necessary use cases and can provide more detailed direction which may not include all this icon variations.

**Comment by didoo** [comment]
> Sorry if there was a miscommunication somewhere, but my intention wasn't for this to be built as it's own component yet. What we're doing in Figma is only to provide the bare minimum of support for this feature as it's used within the dropdown (so as to avoid a "Frankenstein" of nested components) and to only expose it as a part of the dropdown. It's a bandaid until we can officially build and support the individual component. Once it's prioritized and we can start working on it, we'll have a better understanding of all the necessary use cases and can provide more detailed direction which may not include all this icon variations.

No problem at all, @heatherlarsen. I am going to move this ticket to "Draft" and we'll pick it up later, when it's time for the proper implementation (and there's been a component audit and the design specs are defined).

**Comment by MelSumner** [comment]
I don't think we need this anymore, do we?

**Comment by didoo** [comment]
@MelSumner mmm, yes. Sooner or later we will have to implement this as "discrete" component (it's not used only in the dropdown). We are discussing if working on this in the next 6 weeks sprint at the moment.

**Comment by didoo** [comment]
Closing this for now. Will re-open when we will work on this component.

**Pull request closed without merging**
