### PR TITLE
Fix missed semantic token update

### PR DESCRIPTION
**Pull request by didoo**
## :pushpin: Summary

Not sure how, but I missed one semantic token replacement (likely due to some merged branch that contained this update).

## :white_check_mark: Reviewer's checklist

- [ ] +1 Percy if applicable

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by heatherlarsen — APPROVED** [review]
Ah, good catch!

**Comment by Dhaulagiri** [comment]
@didoo should this have a changeset?

**Comment by didoo** [comment]
> @didoo should this have a changeset?

I thought about it. Likely not, we replaced one token with another but the UI remains exactly the same. Didn't want to add "noise" to the releases.

**Comment by Dhaulagiri** [comment]
That makes sense, but in order for consumers to actually get this change it needs to be released, correct?

**Comment by didoo** [comment]
> That makes sense, but in order for consumers to actually get this change it needs to be released, correct?

Yes, but I imagine that sooner or later we will do a release, and it will include also this change.

**Pull request merged**
