### PR TITLE
Error page fixes part 1/n

### PR DESCRIPTION
**Pull request by Dhaulagiri**
### :pushpin: Summary

* [x] pre-render the error route (missed this before)
* [x] add some dimensions to the image
* [x] adjust styles to account for sidebar
* [ ] Probably in a followup PR - figure out why vercel is going index -> error page instead of directly to it

### :link: External links

Jira ticket: [HDS-1309](https://hashicorp.atlassian.net/browse/HDS-1309)

[HDS-1309]: https://hashicorp.atlassian.net/browse/HDS-1309?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
> pre-render the error route

This slightly improves the situation in that once you get to the error page, reloading it will apply the correct styles

**Review by didoo — APPROVED** [review]

**Comment by MelSumner** [comment]
> figure out why vercel is going index -> error page instead of directly to it

Two potential fixes:
1. We don't have [wildcard/globbing](https://guides.emberjs.com/v3.24.0/routing/defining-your-routes/#toc_wildcard--globbing-routes) set up in our `router.js` file.
2. Vercel might need a config file like Netlify does ([example](https://github.com/MelSumner/a11y-automation/blob/main/.netlifyredirects))

**Comment by Dhaulagiri** [comment]
1) I think we do but it's to render the `show` routes?

2) is something I was wondering as well as the prember docs [seem to indicate as much](https://github.com/ef4/prember#configuring-your-webserver), and it would conceptually make sense why we're seeing the behavior we're seeing if vercel doesn't know how to route to an error page correctly.

I did try this in a commit in this branch that I've since dropped and it didn't help, but it may be that vercel.json changes don't take effect in a preview app or at least when a vercel.json didn't exist previously. What we could do it try merging a PR with that change just to test in production and we can always revert it if it doesn't work.

**Comment by Dhaulagiri** [comment]
Part of the underlying issue or challenge is that the request doesn't actually trigger a `404` which may be something amiss with our error handling

**Comment by Dhaulagiri** [comment]
Will be fixed in #1074

**Pull request closed without merging**
