### PR TITLE
Updated export of icons from Figma

### PR DESCRIPTION
**Pull request by hashibot-hds**
### :pushpin: Summary

This is an automated PR opened by the Hashibot-HDS using the GitHub Action [Sync & Build Icons](https://github.com/hashicorp/design-system/actions/workflows/open-pull-request-for-icon-update.yml).

### :hammer_and_wrench: Detailed description

`Postgres` service icon added.

### :camera_flash: Screenshots

elephant
[Brand Info](https://www.postgresql.org/about/policies/trademarks/)

### :link: External links

Jira ticket: [HDS-4137](https://hashicorp.atlassian.net/browse/HDS-4137)
***

### 👀 Component checklist

- [ ] A changelog entry was added via [Changesets](https://github.com/changesets/changesets) if needed ([instructions here](https://github.com/hashicorp/design-system/blob/main/packages/flight-icons/CONTRIBUTING.md#updating-the-icons-in-flight-icons) / [expected format here](https://hashicorp.atlassian.net/wiki/spaces/HDS/pages/3243114706/Changelog+authoring+best+practices#New-icons))

[HDS-4137]: https://hashicorp.atlassian.net/browse/HDS-4137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by jorytindall** [comment]
This needs a changset, otherwise everything looks good to go!

**Review by majedelass — APPROVED** [review]
This looks good to me 👍

**Review by alex-ju — APPROVED** [review]
🐘

**Review by zamoore — APPROVED** [review]
🐘 ❤️ Postgres

**Pull request merged**
