### PR TITLE
`ember-flight-icons` clean-up

### PR DESCRIPTION
**Pull request by alex-ju**
### :pushpin: Summary

 - Remove `ember-flight-icons` as a dependency from `showcase` and `website`
 - Remove steps for building `ember-flight-icons` (in `yarn` and CI workflows) and adjust guidance around it
 - Flag the package as deprecated in the main readme file

### :link: External links

Jira ticket: [HDS-3400](HDS-3400)

***

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

[HDS-3400]: https://hashicorp.atlassian.net/browse/HDS-3400?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by aklkv — APPROVED** [review]
🎉

**Comment by Dhaulagiri** [comment]
It looks like all the icons are missing from the built preview apps 🤔

**Comment by alex-ju** [comment]
> It looks like all the icons are missing from the built preview apps 🤔

indeed, the instance initializer was not added to the package. preparing to merge #2433 to fix this issue

**Review by didoo — APPROVED** [review]
Using your branch I did a full-text search for `ember-flight-` and I found [an instance](https://github.com/hashicorp/design-system/blob/main/website/lib/changelog/generate-changelog-markdown-files.mjs#L16-L17) where maybe we should also make changes? (maybe the intention is to remove the [release notes](https://helios.hashicorp.design/whats-new/release-notes?tab=ember%20flight%20icons) for EmberFlightIcons later?)

**Comment by alex-ju** [comment]
> maybe the intention is to remove the [release notes](https://helios.hashicorp.design/whats-new/release-notes?tab=ember%20flight%20icons) for EmberFlightIcons later?

yes, but I'm thinking of leaving it there until most projects no longer use it

**Pull request merged**
