### PR TITLE
Update package.json info

### PR DESCRIPTION
**Pull request by amyrlam**
## :pushpin: Summary

Noticed this when working on https://github.com/hashicorp/design-system/pull/28
- Update repo to package, so npm can read the package README for public packages
- Removed `contributors` as seemed like the `author` was sufficient

***

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by didoo — APPROVED** [review]
LGTM

**Review by Dhaulagiri — DISMISSED** [review]
Per the [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#repository) it looks like the respository field should be something like this:

```
"repository": {
    "type": "git",
    "url": "https://github.com/hashicorp/design-system.git",
    "directory": "packages/ember-flight-icons"
  }
```

**Review by Dhaulagiri — APPROVED** [review]
Nice!

**Comment by amyrlam** [comment]
We'll probably remove figma-scripting, but I'll merge this in first

**Pull request merged**
