### PR TITLE
updated stepper indicator docs w/a11y info

### PR DESCRIPTION
**Pull request by MelSumner**
### :pushpin: Summary

If merged, this PR updates the stepper indicator docs for accuracy.

### 👀 How to review

👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by jorytindall — APPROVED** [review]
Everything here makes sense, thank you for the points on grammar!

**Comment by MelSumner** [comment]
@jorytindall do you have access to Percy to approve? If not, @alex-ju or @Dhaulagiri would you approve the Percy please?

**Comment by jorytindall** [comment]
Yep, done and done!

**Comment by alex-ju** [comment]
late to the party – looks good! PR and VRT already approved

**Pull request merged**
