### PR TITLE
"Dropdown" component / Add design guidelines

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

This resolves: #229 

### :hammer_and_wrench: Detailed description

In this PR I have:
- added “design guidelines” for “Dropdown” component

Preview: https://hds-components-git-dropdown-add-design-guidelines-hashicorp.vercel.app/components/dropdown

***

### 👀 How to review

👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by heatherlarsen** [comment]
@didoo For some reason the screenshot is getting cut off slightly on the left side.

Screen Shot 2022-04-19 at 8 47 15 AM

**Comment by didoo** [comment]
> @didoo For some reason the screenshot is getting cut off slightly on the left side.

Ah, the shadow! Let me redo it.

**Comment by didoo** [comment]
@heatherlarsen can you check now?

**Review by heatherlarsen — APPROVED** [review]
lgtm!

**Pull request merged**
