### PR TITLE
Compressed Image Assets

### PR DESCRIPTION
**Pull request by hashibot-hds**
Images automagically compressed by [Calibre](https://calibreapp.com)'s [image-actions](https://github.com/marketplace/actions/image-actions) ✨

Compression reduced images by <strong>23.8%</strong>, saving <strong>1.40 MB</strong>.

| Filename | Before | After | Improvement |
| -------- | ------ | ----- | ----------- |
| <code>website/public/assets/components/accordion/content-custom.png</code> | 59.03 KB | 44.23 KB | -25.1% |
| <code>website/public/assets/components/alert/ordering-alerts-type.png</code> | 72.89 KB | 54.68 KB | -25.0% |
| <code>website/public/assets/components/app-footer/app-footer-additional-links.png</code> | 11.03 KB | 6.88 KB | -37.6% |
| <code>website/public/assets/components/app-footer/app-footer-anatomy.png</code> | 46.81 KB | 33.10 KB | -29.3% |
| <code>website/public/assets/components/app-footer/app-footer-dark.png</code> | 14.08 KB | 9.83 KB | -30.2% |
| <code>website/public/assets/components/app-footer/app-footer-extra-content-do.png</code> | 18.44 KB | 11.99 KB | -35.0% |
| <code>website/public/assets/components/app-footer/app-footer-extra-content.png</code> | 16.21 KB | 10.64 KB | -34.3% |
| <code>website/public/assets/components/app-footer/app-footer-items.png</code> | 9.97 KB | 6.32 KB | -36.6% |
| <code>website/public/assets/components/app-footer/app-footer-large.png</code> | 15.71 KB | 9.92 KB | -36.9% |
| <code>website/public/assets/components/app-footer/app-footer-legal-links.png</code> | 12.40 KB | 7.82 KB | -37.0% |
| <code>website/public/assets/components/app-footer/app-footer-order-priority.png</code> | 33.19 KB | 26.85 KB | -19.1% |
| <code>website/public/assets/components/app-footer/app-footer-small.png</code> | 21.28 KB | 13.45 KB | -36.8% |
| <code>website/public/assets/components/badge/badge-inverted-dont.png</code> | 34.07 KB | 24.49 KB | -28.1% |
| <code>website/public/assets/components/code-block/code-block-focus-header.png</code> | 28.75 KB | 22.97 KB | -20.1% |
| <code>website/public/assets/components/code-block/code-block-focus-no-header.png</code> | 18.31 KB | 15.08 KB | -17.7% |
| <code>website/public/assets/components/code-block/code-block-line-selection.png</code> | 22.74 KB | 19.19 KB | -15.6% |
| <code>website/public/assets/components/copy/copy-snippet-table-do.png</code> | 71.54 KB | 51.40 KB | -28.2% |
| <code>website/public/assets/components/flyout/flyout-sizing.png</code> | 297.54 KB | 280.57 KB | -5.7% |
| <code>website/public/assets/components/form/checkbox/checkbox-indeterminate-do.png</code> | 103.51 KB | 81.64 KB | -21.1% |
| <code>website/public/assets/components/form/checkbox/checkbox-indeterminate-dont.png</code> | 38.87 KB | 34.79 KB | -10.5% |
| <code>website/public/assets/components/form/primitives/character-count-defaults-filled.png</code> | 18.87 KB | 15.13 KB | -19.8% |
| <code>website/public/assets/components/form/primitives/character-count-dont-helper-text.png</code> | 16.14 KB | 12.17 KB | -24.6% |
| <code>website/public/assets/components/reveal/content-type-dont.png</code> | 32.52 KB | 24.38 KB | -25.0% |
| <code>website/public/assets/components/table/badge-table-null-value.png</code> | 67.42 KB | 53.22 KB | -21.1% |
| <code>website/public/assets/components/table/center-justified-alignment.png</code> | 62.62 KB | 48.73 KB | -22.2% |
| <code>website/public/assets/components/table/different-badge-sizes.png</code> | 37.84 KB | 32.07 KB | -15.3% |
| <code>website/public/assets/components/table/end-alignment-example-02.png</code> | 59.43 KB | 47.77 KB | -19.6% |
| <code>website/public/assets/components/table/end-alignment-example.png</code> | 39.29 KB | 31.48 KB | -19.9% |
| <code>website/public/assets/components/table/end-alignment-variable-length.png</code> | 68.73 KB | 56.94 KB | -17.2% |
| <code>website/public/assets/components/table/icon-grouping.png</code> | 61.21 KB | 48.00 KB | -21.6% |
| <code>website/public/assets/components/table/icon-product-branding.png</code> | 57.08 KB | 44.94 KB | -21.3% |
| <code>website/public/assets/components/table/icon-status.png</code> | 60.23 KB | 47.33 KB | -21.4% |
| <code>website/public/assets/components/table/icon-tile-product-branding.png</code> | 59.28 KB | 48.35 KB | -18.4% |
| <code>website/public/assets/components/table/icon-without-label.png</code> | 51.64 KB | 42.12 KB | -18.4% |
| <code>website/public/assets/components/table/large-badge-in-table.png</code> | 55.01 KB | 42.80 KB | -22.2% |
| <code>website/public/assets/components/table/link-example.png</code> | 64.74 KB | 60.90 KB | -5.9% |
| <code>website/public/assets/components/table/longform-content-links.png</code> | 92.21 KB | 70.03 KB | -24.1% |
| <code>website/public/assets/components/table/multi-select-cells.png</code> | 64.88 KB | 49.70 KB | -23.4% |
| <code>website/public/assets/components/table/multi-select-header.png</code> | 6.73 KB | 5.93 KB | -11.9% |
| <code>website/public/assets/components/table/multiple-links.png</code> | 76.82 KB | 68.18 KB | -11.2% |
| <code>website/public/assets/components/table/null-data-set-in-a-table.png</code> | 24.04 KB | 17.25 KB | -28.2% |
| <code>website/public/assets/components/table/null-empty-cells.png</code> | 49.02 KB | 38.21 KB | -22.1% |
| <code>website/public/assets/components/table/null-value-badge-example.png</code> | 75.47 KB | 61.35 KB | -18.7% |
| <code>website/public/assets/components/table/null-value-cause-tooltip.png</code> | 87.46 KB | 71.90 KB | -17.8% |
| <code>website/public/assets/components/table/null-value-comparative-value.png</code> | 53.04 KB | 41.42 KB | -21.9% |
| <code>website/public/assets/components/table/null-value-fallback-em-dash.png</code> | 52.05 KB | 42.48 KB | -18.4% |
| <code>website/public/assets/components/table/null-value-fallback-na.png</code> | 57.78 KB | 47.10 KB | -18.5% |
| <code>website/public/assets/components/table/null-value-text-example.png</code> | 56.43 KB | 43.80 KB | -22.4% |
| <code>website/public/assets/components/table/outlined-badge-within-table.png</code> | 40.58 KB | 32.01 KB | -21.1% |
| <code>website/public/assets/components/table/start-alignment-example.png</code> | 61.55 KB | 47.46 KB | -22.9% |
| <code>website/public/assets/components/table/table-alignment-do.png</code> | 6.05 KB | 5.04 KB | -16.8% |
| <code>website/public/assets/components/table/table-alignment-dont.png</code> | 6.05 KB | 5.05 KB | -16.6% |
| <code>website/public/assets/components/table/table-cell-focus-do.png</code> | 28.89 KB | 22.70 KB | -21.4% |
| <code>website/public/assets/components/table/table-cell-select-anatomy.png</code> | 13.32 KB | 10.22 KB | -23.2% |
| <code>website/public/assets/components/table/table-col-placement.png</code> | 13.20 KB | 11.27 KB | -14.6% |
| <code>website/public/assets/components/table/table-density-small-badge.png</code> | 78.58 KB | 66.72 KB | -15.1% |
| <code>website/public/assets/components/table/table-density.png</code> | 10.38 KB | 7.78 KB | -25.1% |
| <code>website/public/assets/components/table/table-header-anatomy.png</code> | 14.33 KB | 11.18 KB | -22.0% |
| <code>website/public/assets/components/table/table-header-select-anatomy.png</code> | 17.06 KB | 13.53 KB | -20.7% |
| <code>website/public/assets/components/table/table-row-placement.png</code> | 12.00 KB | 10.31 KB | -14.1% |
| <code>website/public/assets/components/table/table-sort-button-sorted-states.png</code> | 11.35 KB | 10.10 KB | -11.0% |
| <code>website/public/assets/components/table/table-sort-button-states.png</code> | 11.90 KB | 10.61 KB | -10.9% |
| <code>website/public/assets/components/table/table-sorting.png</code> | 11.25 KB | 7.98 KB | -29.0% |
| <code>website/public/assets/components/table/table-striping.png</code> | 58.67 KB | 42.20 KB | -28.1% |
| <code>website/public/assets/components/table/table-tooltip-dont.png</code> | 73.23 KB | 59.37 KB | -18.9% |
| <code>website/public/assets/components/table/table-tooltip-example.png</code> | 63.13 KB | 48.26 KB | -23.5% |
| <code>website/public/assets/components/table/with-service-icon.png</code> | 59.21 KB | 47.28 KB | -20.1% |
| <code>website/public/assets/components/tabs/tab-size.png</code> | 29.40 KB | 22.37 KB | -23.9% |
| <code>website/public/assets/components/tabs/tab-usage-example-02.png</code> | 85.67 KB | 63.01 KB | -26.4% |
| <code>website/public/assets/components/toast/toast-anatomy.png</code> | 50.66 KB | 39.07 KB | -22.9% |
| <code>website/public/assets/illustrations/components/accordion.jpg</code> | 53.71 KB | 40.62 KB | -24.4% |
| <code>website/public/assets/illustrations/components/alert.jpg</code> | 22.23 KB | 17.34 KB | -22.0% |
| <code>website/public/assets/illustrations/components/app-footer.jpg</code> | 11.22 KB | 9.59 KB | -14.6% |
| <code>website/public/assets/illustrations/components/application-state.jpg</code> | 11.95 KB | 10.51 KB | -12.0% |
| <code>website/public/assets/illustrations/components/badge-count.jpg</code> | 10.57 KB | 8.46 KB | -19.9% |
| <code>website/public/assets/illustrations/components/badge.jpg</code> | 10.25 KB | 8.23 KB | -19.7% |
| <code>website/public/assets/illustrations/components/breadcrumb.jpg</code> | 13.37 KB | 10.47 KB | -21.7% |
| <code>website/public/assets/illustrations/components/button-set.jpg</code> | 15.41 KB | 13.11 KB | -14.9% |
| <code>website/public/assets/illustrations/components/button.jpg</code> | 11.06 KB | 10.45 KB | -5.5% |
| <code>website/public/assets/illustrations/components/card.jpg</code> | 37.32 KB | 26.65 KB | -28.6% |
| <code>website/public/assets/illustrations/components/code-block.jpg</code> | 61.23 KB | 43.06 KB | -29.7% |
| <code>website/public/assets/illustrations/components/copy-button.jpg</code> | 12.47 KB | 10.90 KB | -12.7% |
| <code>website/public/assets/illustrations/components/copy-snippet.jpg</code> | 8.64 KB | 7.61 KB | -12.0% |
| <code>website/public/assets/illustrations/components/dropdown.jpg</code> | 29.89 KB | 22.66 KB | -24.2% |
| <code>website/public/assets/illustrations/components/flyout.jpg</code> | 49.99 KB | 33.79 KB | -32.4% |
| <code>website/public/assets/illustrations/components/form/checkbox.jpg</code> | 13.44 KB | 11.30 KB | -15.9% |
| <code>website/public/assets/illustrations/components/form/file-input.jpg</code> | 12.01 KB | 10.77 KB | -10.4% |
| <code>website/public/assets/illustrations/components/form/masked-input.jpg</code> | 19.52 KB | 15.99 KB | -18.1% |
| <code>website/public/assets/illustrations/components/form/primitives.jpg</code> | 12.08 KB | 11.12 KB | -7.9% |
| <code>website/public/assets/illustrations/components/form/radio-card.jpg</code> | 35.81 KB | 26.17 KB | -26.9% |
| <code>website/public/assets/illustrations/components/form/radio.jpg</code> | 12.68 KB | 10.76 KB | -15.2% |
| <code>website/public/assets/illustrations/components/form/segmented-group.jpg</code> | 11.70 KB | 10.98 KB | -6.2% |
| <code>website/public/assets/illustrations/components/form/select.jpg</code> | 18.23 KB | 15.27 KB | -16.2% |
| <code>website/public/assets/illustrations/components/form/text-input.jpg</code> | 19.65 KB | 15.53 KB | -21.0% |
| <code>website/public/assets/illustrations/components/form/textarea.jpg</code> | 28.22 KB | 22.17 KB | -21.5% |
| <code>website/public/assets/illustrations/components/form/toggle.jpg</code> | 10.27 KB | 8.34 KB | -18.8% |
| <code>website/public/assets/illustrations/components/icon-tile.jpg</code> | 10.78 KB | 8.63 KB | -20.0% |
| <code>website/public/assets/illustrations/components/link/inline.jpg</code> | 13.40 KB | 11.23 KB | -16.2% |
| <code>website/public/assets/illustrations/components/link/standalone.jpg</code> | 11.91 KB | 9.38 KB | -21.2% |
| <code>website/public/assets/illustrations/components/modal.jpg</code> | 35.56 KB | 25.99 KB | -26.9% |
| <code>website/public/assets/illustrations/components/page-header.jpg</code> | 19.92 KB | 16.16 KB | -18.9% |
| <code>website/public/assets/illustrations/components/pagination.jpg</code> | 8.62 KB | 8.29 KB | -3.7% |
| <code>website/public/assets/illustrations/components/reveal.jpg</code> | 20.21 KB | 16.31 KB | -19.3% |
| <code>website/public/assets/illustrations/components/separator.jpg</code> | 17.33 KB | 13.89 KB | -19.9% |
| <code>website/public/assets/illustrations/components/side-nav.jpg</code> | 42.23 KB | 30.52 KB | -27.7% |
| <code>website/public/assets/illustrations/components/stepper.jpg</code> | 9.93 KB | 7.89 KB | -20.6% |
| <code>website/public/assets/illustrations/components/table.jpg</code> | 28.56 KB | 22.64 KB | -20.7% |
| <code>website/public/assets/illustrations/components/tabs.jpg</code> | 13.68 KB | 11.35 KB | -17.0% |
| <code>website/public/assets/illustrations/components/tag.jpg</code> | 12.73 KB | 10.44 KB | -18.0% |
| <code>website/public/assets/illustrations/components/text.jpg</code> | 25.47 KB | 19.65 KB | -22.8% |
| <code>website/public/assets/illustrations/components/toast.jpg</code> | 53.36 KB | 36.12 KB | -32.3% |
| <code>website/public/assets/illustrations/components/tooltip.jpg</code> | 15.62 KB | 13.34 KB | -14.6% |
| <code>website/public/assets/illustrations/foundations/accessibility.jpg</code> | 12.86 KB | 10.20 KB | -20.7% |
| <code>website/public/assets/illustrations/foundations/border.jpg</code> | 21.68 KB | 17.76 KB | -18.1% |
| <code>website/public/assets/illustrations/foundations/colors.jpg</code> | 19.16 KB | 15.11 KB | -21.2% |
| <code>website/public/assets/illustrations/foundations/elevation.jpg</code> | 34.30 KB | 23.76 KB | -30.7% |
| <code>website/public/assets/illustrations/foundations/focus-ring.jpg</code> | 15.09 KB | 11.94 KB | -20.9% |
| <code>website/public/assets/illustrations/foundations/tokens.jpg</code> | 18.30 KB | 15.57 KB | -14.9% |
| <code>website/public/assets/illustrations/foundations/typography.jpg</code> | 17.01 KB | 13.30 KB | -21.8% |
| <code>website/public/assets/illustrations/home-abstract-small.jpg</code> | 12.61 KB | 10.78 KB | -14.5% |
| <code>website/public/assets/illustrations/home-abstract.jpg</code> | 89.71 KB | 76.44 KB | -14.8% |
| <code>website/public/assets/illustrations/icons/library.jpg</code> | 13.64 KB | 10.88 KB | -20.3% |
| <code>website/public/assets/illustrations/icons/usage-guidelines.jpg</code> | 19.07 KB | 15.63 KB | -18.0% |
| <code>website/public/assets/illustrations/layouts/app-frame.jpg</code> | 15.25 KB | 12.15 KB | -20.3% |
| <code>website/public/assets/illustrations/overrides/power-select.jpg</code> | 41.60 KB | 30.05 KB | -27.8% |
| <code>website/public/assets/illustrations/patterns/button-organization.jpg</code> | 54.02 KB | 38.27 KB | -29.2% |
| <code>website/public/assets/illustrations/patterns/filter-patterns.jpg</code> | 13.73 KB | 11.73 KB | -14.6% |
| <code>website/public/assets/illustrations/patterns/form-patterns.jpg</code> | 19.30 KB | 16.42 KB | -14.9% |
| <code>website/public/assets/illustrations/patterns/table-multi-select.jpg</code> | 197.86 KB | 21.53 KB | -89.1% |
| <code>website/public/assets/illustrations/principles/consider-everyone.jpg</code> | 13.98 KB | 10.92 KB | -21.9% |
| <code>website/public/assets/illustrations/principles/design-in-context.jpg</code> | 20.93 KB | 15.58 KB | -25.6% |
| <code>website/public/assets/illustrations/principles/guidance-over-control.jpg</code> | 12.21 KB | 9.52 KB | -22.1% |
| <code>website/public/assets/illustrations/principles/invite-feedback.jpg</code> | 15.50 KB | 12.11 KB | -21.8% |
| <code>website/public/assets/illustrations/principles/quality-by-default.jpg</code> | 14.37 KB | 11.33 KB | -21.2% |
| <code>website/public/assets/illustrations/principles/rooted-in-reality.jpg</code> | 14.54 KB | 11.24 KB | -22.7% |
| <code>website/public/assets/illustrations/utilities/disclosure-primitive.jpg</code> | 35.83 KB | 26.95 KB | -24.8% |
| <code>website/public/assets/illustrations/utilities/interactive.jpg</code> | 18.97 KB | 14.90 KB | -21.4% |
| <code>website/public/assets/illustrations/utilities/menu-primitive.jpg</code> | 35.83 KB | 26.95 KB | -24.8% |
| <code>website/public/assets/logos/share-card.jpg</code> | 47.10 KB | 39.05 KB | -17.1% |
| <code>website/public/assets/patterns/button-organization/using-right-alignment.png</code> | 49.74 KB | 39.02 KB | -21.5% |
| <code>website/public/assets/patterns/filter-patterns/example-data-set-tabular-data.png</code> | 78.39 KB | 61.16 KB | -22.0% |
| <code>website/public/assets/patterns/filter-patterns/layout-filter-bar.png</code> | 57.78 KB | 45.15 KB | -21.9% |
| <code>website/public/assets/patterns/filter-patterns/overflow-filter-bar-multiple-rows.png</code> | 62.19 KB | 48.00 KB | -22.8% |
| <code>website/public/assets/patterns/table-multi-select/multi-select-preview-image.png</code> | 89.47 KB | 75.09 KB | -16.1% |
| <code>website/public/assets/patterns/table-multi-select/multi-select-reflow-example.png</code> | 67.63 KB | 57.99 KB | -14.2% |
| <code>website/public/assets/patterns/table-multi-select/types-of-messages.png</code> | 34.44 KB | 25.45 KB | -26.1% |
| <code>wiki/images/doc-a11y-badge.png</code> | 12.25 KB | 8.95 KB | -27.0% |
| <code>wiki/images/doc-badge.png</code> | 24.23 KB | 13.89 KB | -42.7% |
| <code>wiki/images/doc-banner.png</code> | 34.64 KB | 22.44 KB | -35.2% |
| <code>wiki/images/doc-code-block-not-executed.png</code> | 19.88 KB | 11.51 KB | -42.1% |
| <code>wiki/images/doc-code-block-self-executed.png</code> | 28.32 KB | 15.50 KB | -45.3% |
| <code>wiki/images/doc-code-block-simple.png</code> | 20.49 KB | 11.25 KB | -45.1% |
| <code>wiki/images/doc-copy-button.png</code> | 46.84 KB | 24.88 KB | -46.9% |
| <code>wiki/images/doc-dodont.png</code> | 26.51 KB | 13.66 KB | -48.5% |
| <code>wiki/images/doc-figma-clip-content.png</code> | 18.15 KB | 9.82 KB | -45.9% |
| <code>wiki/images/doc-figma-show-in-exports.png</code> | 11.23 KB | 5.90 KB | -47.5% |
| <code>wiki/images/doc-folder-structure.png</code> | 148.80 KB | 106.65 KB | -28.3% |
| <code>wiki/images/doc-grid-stage.png</code> | 116.45 KB | 95.08 KB | -18.3% |
| <code>wiki/images/doc-grid-wrapper.png</code> | 127.85 KB | 101.93 KB | -20.3% |
| <code>wiki/images/doc-inline-code.png</code> | 12.98 KB | 8.62 KB | -33.6% |

522 images did not require optimisation.

### CODE REVIEW

**Review by alex-ju — APPROVED** [review]
`website/public/assets/illustrations/patterns/table-multi-select.jpg`	197.86 KB	21.53 KB	**-89.1%** 🙀

**Comment by jorytindall** [comment]
> `website/public/assets/illustrations/patterns/table-multi-select.jpg` 197.86 KB 21.53 KB **-89.1%** 🙀

This is wild to me, that illustration _looks_ so simple!

**Review by jorytindall — APPROVED** [review]
I loosely followed the PR to implement this action, but can't recall whether there's an option for setting the quality. Generally a lot of these image compression tools let you choose a percentage up to 100%, more just asking out of curiosity about whether we might actually be able to save more without sacrificing the visual appearance. This is pretty awesome though!

**Comment by Dhaulagiri** [comment]
@jorytindall great question. The compression is [configurable](https://github.com/calibreapp/image-actions?tab=readme-ov-file#control-image-quality-settings), but the default is 80%. It would be possible to experiment with that if we wanted to.

**Review by MelSumner — APPROVED** [review]
This is great. I've been using something automated like this in some of my other projects to save me from having to do it manually. Thanks for getting this set up!

**Review by heatherlarsen — APPROVED** [review]
I spot-checked a bunch of images and didn't see any issues. Looks good to me 👍🏻

**Pull request merged**
