### PR TITLE
"Dropdown" component - Add support for "LinkToExternal" engine component (08)

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

This is a draft PR to discuss (using real code) a possible solution to the problem of supporting `LinkToExternal` links in our components (these are very special kind of links, similar to the `<LinkTo>` but specific for Ember engines.

More context:
- https://github.com/hashicorp/cloud-ui/pull/2362#issuecomment-1097909966
- https://hashicorp.slack.com/archives/CPB8GS9QT/p1649868202616679

👉 Notice: if you want to test it yourself and play with the code:
- clone the repo, then do a `yarn install` in the root of the project, and then call `yarn start` in the folder `packages/components`
- this will build the dev version of the dummy website and run it as localhost (you will see the port in the CLI)
- open the localhost website and navigate to the `Dropdown` page

### :hammer_and_wrench: Detailed description

In this PR I have:
- added `ember-engines` as both _devDependency_ and _peerDependency_
  -  as suggested by Matthew Irish [in this conversation in Slack](https://hashicorp.slack.com/archives/CPB8GS9QT/p1649868722882949?thread_ts=1649868202.616679&cid=CPB8GS9QT)
  - we need both [according to the documentation](https://ember-engines.com/docs/quickstart#:~:text=A%20quick%20note%2C%20Engines%20should%20have%20ember%2Dengines%20listed%20as%20a%20devDependency%20and%20peerDependency)
- updated the `list-item/interactive` to support also a `LinkToExternal` via a `@isRouteExternal` prop
- changed one of the routes in the dropdown doc page to use an external route

🚨 **Notice**: this triggers an error in console, I suspect we need to [configure the app to support engines](https://ember-engines.com/docs/quickstart)

screenshot_1322

I am not sure how to proceed from here, is beyond my Ember knowledge.

***

### 👀 How to review

👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202122650634746
  - https://app.asana.com/0/0/1202122650634755

### CODE REVIEW

**Comment by MelSumner** [comment]
Are we sure that we need to add ember-engines as a peer dependency? This seems strange to me. Engines should be able to consume and use the addon w/o us specifically adding it, shouldn't they?

**Comment by didoo** [comment]
@MelSumner this is is still in draft because likely will be solved (if approved) by #216

**Review by MelSumner — APPROVED** [review]
Apologies for not getting to this sooner, if we need to ship this to support engines then we should ship it.

**Comment by didoo** [comment]
closing this one, since it will be fixed by #216 and #217

**Pull request closed without merging**
