### PR TITLE
Fix duplicate `react-svg` export in `flight-icon`

### LINKED ISSUE #522: Bug report: Duplicate exports in flight-icons/svg-react/index.ts
## IS: Current behavior
version: `@hashicorp/flight-icons@2.8.0`

```
./node_modules/@hashicorp/flight-icons/svg-react/index.ts:45:10
--
13:52:59.266 | Type error: Duplicate identifier 'IconAzureVms24'.
13:52:59.266 |  
13:52:59.266 |    43 | export { IconAzureColor24 } from './azure-color-24';
13:52:59.266 |    44 | export { IconAzureColor16 } from './azure-color-16';
13:52:59.266 | >  45 | export { IconAzureVms24 } from './azure-vms-24';
13:52:59.266 |                  ^
13:52:59.266 |    46 | export { IconAzureVms16 } from './azure-vms-16';
13:52:59.266 |    47 | export { IconAzureVmsColor24 } from './azure-vms-color-24';
13:52:59.266 |    48 | export { IconAzureVmsColor16 } from './azure-vms-color-16';
```

## SHOULD BE: Expected behavior

No duplicate export declarations.

### PR DESCRIPTION
**Pull request by alex-ju**
### :pushpin: Summary

Fix duplicate `react-svg` export in `flight-icon`

### :hammer_and_wrench: Detailed description

These were accidentally added twice in [#481](https://github.com/hashicorp/design-system/pull/481/files#diff-7a4a94ca2bd0e40992f860d9ac74645f3a06e758ad5308a241e4800d1e13862dR45-R47) – possible due to the branch being out-of-sync. While not super familiar with the automation in `flight-icon`, my understanding is that removing these manually will fix the issue and won't affect (or be affected by) any further updates.

### :link: External links

Fixes #522 

***

### 👀 How to review

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
There is more to do here to fix this as these icons are duplicated in the source catalog. Example of `azure-vms-16` existing [here](https://github.com/hashicorp/design-system/blob/597b213b8a51c081f490f7fa34d2f4a84b380f5b/packages/flight-icons/catalog.json#L529) and [here](https://github.com/hashicorp/design-system/blob/597b213b8a51c081f490f7fa34d2f4a84b380f5b/packages/flight-icons/catalog.json#L421) when it should only be in there once. 

See the screenshot from the website as well showing the duplication:

Screen Shot 2022-08-05 at 08 29 30

I asked @cveigt to double check the Figma files to see if things are duplicated there and then we can try to re-run the export.

**Comment by Dhaulagiri** [comment]
Looking at [the contents of the export directory](https://github.com/hashicorp/design-system/tree/main/packages/flight-icons/svg) I don't actually see any duplication which leads me to believe that somehow the entries got duplicated in catalog.json and the fix here is to manually remove the duplicates there.

**Comment by cveigt** [comment]
@Dhaulagiri I checked them on Figma, and "azure-aks" had one of the layers named as "azure-vms", which I guess makes it export whichever icon has that name twice. It must have been an oversight on my side. I've just fixed it and re-published the library.

See the Figma catalog below:

Before fix:
Screen Shot 2022-08-05 at 6 48 21 AM

After:
Screen Shot 2022-08-05 at 6 54 13 AM

Could you please try re-running the export?

**Comment by Dhaulagiri** [comment]
This will be fixed in https://github.com/hashicorp/design-system/pull/524

**Pull request closed without merging**
