### PR TITLE
Update Helios logo in main readme file

### PR DESCRIPTION
**Pull request by alex-ju**
### :pushpin: Summary

Suggesting a potential change for the header of our main readme file – using the one we have in our emailing template.

### :hammer_and_wrench: Detailed description

This is subjective and ultimately comes down to personal preference, but I thought it's worth sharing this minor proposal with the team. Share your thoughts or 👍 / 👎

#### Preview

[Current](https://github.com/hashicorp/design-system/blob/main/README.md) / [Proposed](https://github.com/hashicorp/design-system/blob/9bcb68039a40a2b9a54363cc6d6bce4ac4eb72bf/README.md) 

____

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by KristinLBradley — APPROVED** [review]
Looks good to me

**Comment by jorytindall** [comment]
No overly opinionated on this, but in a dark theme (or dark background) this looks a little strange to me. There's probably not a way to conditionally show something based on theme in this case and I don't want to overthink it, just noting it here though.
Screenshot 2024-02-29 at 10 36 26 AM

**Comment by alex-ju** [comment]
> No overly opinionated on this, but in a dark theme (or dark background) this looks a little strange to me. There's probably not a way to conditionally show something based on theme in this case and I don't want to overthink it, just noting it here though.

I had the same thought just a few minutes ago – this would be valuable especially as the dark theme is now the default one in GitHub..

**Comment by jorytindall** [comment]
@alex-ju I did some quick poking around and Supabase actually does this in their readme https://github.com/supabase/supabase

```
<p align="center">
  <img src="https://user-images.githubusercontent.com/8291514/213727234-cda046d6-28c6-491a-b284-b86c5cede25d.png#gh-light-mode-only">
  <img src="https://user-images.githubusercontent.com/8291514/213727225-56186826-bee8-43b5-9b15-86e839d89393.png#gh-dark-mode-only">
</p>
```
Screenshot 2024-02-29 at 10 47 14 AM
Screenshot 2024-02-29 at 10 47 22 AM

**Comment by alex-ju** [comment]
> @alex-ju I did some quick poking around and Supabase actually does this in their readme 

the fragment method is [going to be deprecated](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to), unfortunately, but I just tested the `prefers-color-scheme` solution and it works well

**Comment by didoo** [comment]
Apparently is an official thing: https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/

An alternative is to use an inline SVG and use `var(--color-fg-default)` for the `fill` attribute of the text part of the "logo" (but we have to test and see if it works)

**Comment by alex-ju** [comment]
Thanks all for entertaining this idea! I will put this to rest for now and try to focus on more relevant matters.

**Pull request closed without merging**
