### PR TITLE
"Dropdown" component - Finalize implementation in code (feature branch)

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

This is the new "feature branch" used to finalize the implementation of the `Dropdown` component.
The following PRs need to be reviewed and merged in this order:

1. #201 - ✅
2. #202 - ✅ (with new issue opened [here](https://github.com/hashicorp/design-system/issues/228))
3. #203 - ✅
4. #204 - ✅
5. #205 - ✅
6. #211 - ✅
7. #212 - ✅
8. #215 - 🤔
9. #234 - ✅
10. #235 - ✅
11. #236 - ✅
12. #243 - ✅
13. #242 - ✅

Once they're all merged (if approved) in this branch, we'll do a final review of the code to make sure we're not missing or forgetting something, and once this PR is approved it can be merged in `main` and the component officially released.

***

### 👀 How to review

👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1202108023378513

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
Reminder that this PR needs a changeset before it goes out. I think probably a changeset in the branches off of this might be easier to capture the mini features/patches being made in them but since those are already merged we'll have to capture that here instead.

**Comment by didoo** [comment]
> Reminder that this PR needs a changeset before it goes out. I think probably a changeset in the branches off of this might be easier to capture the mini features/patches being made in them but since those are already merged we'll have to capture that here instead.

screenshot_1348

**Comment by didoo** [comment]
@MelSumner now it's ready for the final review

**Review by MelSumner — APPROVED** [review]
We reviewed each of these parts individually, and this does not seem to add anything extra.

**Pull request merged**
