### PR TITLE
`Website` - Images optimization

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

While reviewing https://github.com/hashicorp/design-system/pull/1691/ I noticed that the illustration image for the component was not optimized (was able to reduce by 75% its side) which made me realize that we have probably stopped checking this some time ago.

In this PR I am have optimized all the existing assets using a Mac app ([ImageOptim](https://imageoptim.com/mac)) but maybe we should automate the process (@Dhaulagiri) if it's not yet happening in the ember cli build step (frankly, I don't remember, I have a vague recollection we discussed this, and it may be that we decided it was for later to implement).

### :hammer_and_wrench: Detailed description

In this PR I have 
- optimized all the images under the `public/assets` folder

Previews: 
- before: https://helios.hashicorp.design/
- after: https://hds-website-git-website-image-optimization-hashicorp.vercel.app/

### :camera_flash: Screenshots

screenshot_3182

***

### 👀 Component checklist

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by Dhaulagiri** [comment]
> I have a vague recollection we discussed this, and it may be that we decided it was for later to implement

We did capture this [in jira](https://hashicorp.atlassian.net/browse/HDS-1353) but never got around to do it

**Comment by Dhaulagiri** [comment]
Can you have this PR be only the icon for the CodeBlock and make a separate one pointed at `main` for the rest (or make that a commit directly on that PR) so we can merge in the rest of the changes without tying them up with the CodeBlock work?

**Comment by didoo** [comment]
This is not urgent, so as soon as the CodeBlock is merged we merge also this one

**Review by alex-ju — APPROVED** [review]
I don't think ember cli build has compression baked in out of the box – however, we could add an automated step in the future.

**Comment by didoo** [comment]
> I don't think ember cli build has compression baked in out of the box 

@alex-ju unfortunately not.

> however, we could add an automated step in the future.

Tracked here: https://hashicorp.atlassian.net/browse/HDS-1353
(I did a quick spike the other day and... it's not a quick thing to do 😀)

**Review by heatherlarsen — APPROVED** [review]
Great catch! If we can't easily automate the process, is there something we should do after exporting the images from Figma? We can add it as a part of our workflow, if that's easier?

**Comment by didoo** [comment]
> is there something we should do after exporting the images from Figma? We can add it as a part of our workflow, if that's easier?

@heatherlarsen I personally use https://imageoptim.com/mac (which is free). Then drag&drop the images I want to optimize over the window, and wait for the process to complete (it takes some time).
These are the settings I use: 
screenshot_3195

**Pull request merged**
