### PR TITLE
Fix button(s) DOM structure

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

See [Jira ticket](https://hashicorp.atlassian.net/browse/HDS-2866) for details.

### :hammer_and_wrench: Detailed description

In this PR I have:
- updated the `Button` DOM structure to contain only `span` elements
- updated the `Dropdown` button elements DOM structure to contain only `span` elements
- updated the `Link::Standalone` DOM structure to contain only `span` elements

### :link: External links

Jira ticket: https://hashicorp.atlassian.net/browse/HDS-2866

***

### 👀 Component checklist

- [x] Percy was checked for any visual regression
- [x] A11y tests have been run locally (`yarn test:a11y --filter="COMPONENT-NAME"`)
- [x] A changelog entry was added via [Changesets](https://github.com/changesets/changesets) if needed (see [templates here](https://github.com/hashicorp/design-system/blob/main/wiki/Website-Changelog.md#templates-for-npm-packages))

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by KristinLBradley — APPROVED** [review]

**Review by alex-ju — COMMENTED** [review]
If we look at it from a corrective perspective (as in, we realized these should've been `<span>`s and not `<div>`) I would consider them a fix.

**Review by MelSumner — CHANGES_REQUESTED** [review]
I think this needs a patch changeset. 

Looked through things on the preview site and it all appears as I would expect. So once the changeset is added, I have no objection to releasing this.

**Comment by didoo** [comment]
> once the changeset is added, I have no objection to releasing this.

@MelSumner changeset added as `patch` (as suggested).

**Review by KristinLBradley — COMMENTED** [review]
There's some visual changes to widths.

**Comment by didoo** [comment]
> ~There's some visual changes to widths.~
> 
> Sorry my mistake, I see some elements were just pushed down by the added separators in the `TextInput` Showcase.

@KristinLBradley I needed to rebase on `main` to get the Percy test pass (`main` contained the changes introduced with the `CodeBlock`). Not it's all green.

**Review by MelSumner — APPROVED** [review]
👍

**Pull request merged**
