### PR TITLE
updated “button-design-usage” image

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

Updated the button-design-usage” image for the `Button` documentation page

### CODE REVIEW

**Comment by heatherlarsen** [comment]
Design Guidelines

**Review by heatherlarsen — CHANGES_REQUESTED** [review]
This one ended up looking pretty pixelated. I commented with a new screenshot. Can you try that one and see if it's clearer? Thanks!

**Comment by didoo** [comment]
> This one ended up looking pretty pixelated. I commented with a new screenshot. Can you try that one and see if it's clearer? Thanks!

@heatherlarsen probably forgot to export the image at `2x`, pushed a new one now.

**Review by heatherlarsen — APPROVED** [review]
lgtm!

**Pull request merged**
