### PR TITLE
Align page title and main headings to blueprint format

### PR DESCRIPTION
**Pull request by alex-ju**
### :pushpin: Summary

Align page title and main headings in `showcase` to match [blueprint format](https://github.com/hashicorp/design-system/blob/main/showcase/blueprints/hds-component-test/files/app/templates/components/__name__.hbs)

***

### 👀 Component checklist

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by didoo** [comment]
@alex-ju wouldn't have been _better™_ to instead update the blueprint by removing the ` Component` string from the template? 🤔

**Comment by alex-ju** [comment]
> @alex-ju wouldn't have been _better™_ to instead update the blueprint by removing the ` Component` string from the template? 🤔

we can remove 'Component' from the title, but we still have a mix of formats across titles _and_ headings. I'm happy with whatever format, just want them aligned.

**Review by didoo — APPROVED** [review]
Great 🧹🫧🧽 🙌

**Comment by didoo** [comment]
> > @alex-ju wouldn't have been _better™_ to instead update the blueprint by removing the ` Component` string from the template? 🤔
> 
> we can remove 'Component' from the title, but we still have a mix of formats across titles _and_ headings. I'm happy with whatever format, just want them aligned.

Ahh I see. OK, approved then 👍

**Pull request merged**
