### PR TITLE
Update flight icons docs

### PR DESCRIPTION
**Pull request by cveigt**
Updated the Contribution workflow to reflect the new process

### :pushpin: Summary
This PR updates the copy of the contributing guidelines as we no longer use GH issues for icon requests.

### :link: External links

https://hashicorp.atlassian.net/browse/HDS-620

***

### 👀 How to review

👉 Review commit-by-commit
👉 Review by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Comment by cveigt** [comment]
@heatherlarsen I added you as a reviewer since you created the ticket. Updated only the copy for the last step of the contribution workflow because the form is supposed to be a temporary solution, but I wonder if you were thinking of making other changes.

**Comment by cveigt** [comment]
@didoo @Dhaulagiri I'm getting this from the yarn lint
```
Error:   633:113  error  Insert `⏎·····`  prettier
```
Also, getting [this test failure](https://github.com/hashicorp/design-system/actions/runs/3162311179/jobs/5148788861)

I made sure that the branch had the latest changes and tried to update the dependencies running yarn install, but didn't fix the issue.

**Comment by didoo** [comment]
@cveigt I've fixed the linting error. for the other error, let's wait for #599 to be merged, let's rebase/merge `main` and let's see if the error goes away.

**Comment by heatherlarsen** [comment]
@cveigt I wasn't aware the form was a "temporary solution"...what is the long term solution for incoming icon requests?

I had a look at the preview link and left a few comments there.

**Comment by Dhaulagiri** [comment]
@heatherlarsen i'm exploring moving our forms into Jira directly

**Comment by cveigt** [comment]
@didoo I rebased this branch with `main` as you suggested, and the error didn't go away.

**Comment by didoo** [comment]
> @didoo I rebased this branch with `main` as you suggested, and the error didn't go away.

The error was another (it was a test failing). This is a linting error, I've pushed a fix.

**Review by heatherlarsen — APPROVED** [review]
I hope you don't mind, but one of the links to the Dev frame was still off so I pushed a direct commit to fix it since I couldn't figure out how to submit a suggestion for it. Everything else looks good!

**Pull request merged**
