### PR TITLE
`AppFooter`: Change visual alignment to centered (HDS-2960)

### PR DESCRIPTION
**Pull request by KristinLBradley**
### :pushpin: Summary
If merged, this PR changes the `AppFooter` visual alignment from right-aligned to centered.

- **Showcase:** https://hds-showcase-git-hds-2960-app-footer-alignment-hashicorp.vercel.app/components/app-footer

### :camera_flash: Screenshots
TFC - BEFORE (with old footer):
Before_TFC-footer

TFC - AFTER (with Hds::AppFooter):
After_TFC-HdsAppFooter

### :link: External links
- Jira ticket: [HDS-2960](https://hashicorp.atlassian.net/browse/HDS-2960)
- [Figma file](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/branch/sL2NGb1VhZ6i9G8E6UIopl/HDS-Product---Components?type=design&node-id=50549-17068&mode=design&t=pih3PDgo40v8Iwak-0)

***

### 👀 Component checklist

- [x] Percy was checked for any visual regression
- [ ] ~~A11y tests have been run locally (`yarn test:a11y --filter="COMPONENT-NAME"`)~~
- [ ] ~~If documenting a new component, an acceptance test that includes the `a11yAudit` has been added~~
- [x] A changelog entry was added via [Changesets](https://github.com/changesets/changesets) if needed (see [templates here](https://github.com/hashicorp/design-system/blob/main/wiki/Website-Changelog.md#templates-for-npm-packages))

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

[HDS-2960]: https://hashicorp.atlassian.net/browse/HDS-2960?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by didoo — COMMENTED** [review]
All good from the code side. But **before** merging:
- wait for the equivalent change in Figma to be ready to be released
- wait for the images in the documentation to be updated too (could be done in this PR, or in a separate one)

**Comment by KristinLBradley** [comment]
Added screenshots showing the `Hds::AppFooter` within TFC.

One issue, their old footer a property for `this.currentOrganization` as part of their "Support" link href. Not sure where I would put that so it works with the `Hds::AppFooter`. I'd have to create a new JavaScript file.

**Comment by didoo** [comment]
> One issue, their old footer a property for `this.currentOrganization` as part of their "Support" link href. Not sure where I would put that so it works with the `Hds::AppFooter`. I'd have to create a new JavaScript file.
> 
> UPDATE: For now I did this `@hrefForSupport={{if @currentOrganization (support-email-link @currentOrganization) null}}`

@KristinLBradley probably I would work/collaborate with them to find the correct solution (they have better context of their codebase)

**Review by andgen404 — APPROVED** [review]
Changes look good to me 🎉

**Comment by KristinLBradley** [comment]
> All good from the code side. But **before** merging:
> 
> * wait for the equivalent change in Figma to be ready to be released
> * wait for the images in the documentation to be updated too (could be done in this PR, or in a separate one)

Documentation has been updated with new images & Figma component updates from @andgen404 are ready to go.

**Review by jorytindall — APPROVED** [review]

**Pull request merged**
