### PR TITLE
Form controls - Styles updates

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

Now that the `form controls` are almost completely finalized on the design side, it's time to re-check that their styles in CSS match the latest design specs.

### :hammer_and_wrench: Detailed description

In this PR I have:
- created component-level tokens for form controls (as temporary solution, while we wait to implement them in the proper tokens pipeline)
- applied latest styling specs from design (using component-level design tokens) to:
  - `Legend`
  - `Error`
  - `HelperText`
  - `Label`
  - `TextInput`
  - `Textarea`
  - `Select`
  - `Checkbox`
  - `Radio` 
  - `Toggle` 

Previews:
- [Base elements](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/base-elements#showcase)
- [TextInput](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/text-input#showcase)
- [Textarea](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/textarea#showcase)
- [Select](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/select#showcase)
- [Checkbox](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/checkbox#showcase)
- [Radio](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/radio#showcase)
- [Toggle](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/Toggle#showcase)

### :link: External links

- Jira issue: https://hashicorp.atlassian.net/browse/HDS-295

### 🤔 Open questions

- The form controls share a lot of styles in terms of CSS declarations: should we introduce a set of common class names that can be applied to the components (via the `classNames` JS method) to avoid code duplication? In that case, how much is the risk to increase the complexity of the CSS code for the form controls? (eg. where does a style come from? what happens if I change a common file?) 

***

### 👀 How to review

👉 Review commit-by-commit or by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by MelSumner — APPROVED** [review]
Gosh I just love design tokens ^_^

**Comment by heatherlarsen** [comment]
@didoo Just tagged you in a comment on the [Figma version](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/branch/CsGFsY5gotq3YE7USnA0Zr/HDS-Product---Components?node-id=10212%3A26295) of this. Let me know if you'd like to sync about this approach.

**Comment by cveigt** [comment]
@didoo, a couple of things:

- The spacing between fields for vertical groups should be `12px` instead of `20px`. [Figma](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/HDS-Product---Components?node-id=9120%3A23132) for reference.

- I was testing with other browsers and noticed that the control looks very different. All the styles, even the check icon seems to be different or not taking the correct size. It's like it's only applying some of the CSS properties but not all of them.

Screen Shot 2022-07-14 at 11 22 12 PM

The same happens with the `radio` base control.

**Comment by didoo** [comment]
> @didoo, a couple of things:
> 
> * The spacing between fields for vertical groups should be `12px` instead of `20px`. [Figma](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/HDS-Product---Components?node-id=9120%3A23132) for reference.
> * I was testing with other browsers and noticed that the control looks very different. All the styles, even the check icon seems to be different or not taking the correct size. It's like it's only applying some of the CSS properties but not all of them.
> 
> Screen Shot 2022-07-14 at 11 22 12 PM
> 
> The same happens with the `radio` base control.

Not sure which browser you are using. This is what I see opening [this page](https://hds-components-git-form-controls-styles-updates-hashicorp.vercel.app/components/form/checkbox#showcase) in:

Safari:
screenshot_1638

Opera:
screenshot_1639

Firefox:
screenshot_1640

Edge:
screenshot_1641

Maybe the CSS was not properly loaded in your browser, for some reasons?

**Comment by didoo** [comment]
> @didoo Just tagged you in a comment on the [Figma version](https://www.figma.com/file/noyY6dUMDYjmySpHcMjhkN/branch/CsGFsY5gotq3YE7USnA0Zr/HDS-Product---Components?node-id=10212%3A26295) of this. Let me know if you'd like to sync about this approach.

Yes, let's sync (but will be done in a different PR though).

**Comment by heatherlarsen** [comment]
@didoo Ahh, my bad, I thought this was tied to [HDS-297](https://hashicorp.atlassian.net/browse/HDS-297). 👍

**Comment by didoo** [comment]
@heatherlarsen I've added the custom icon for the `Select` element.

**Review by heatherlarsen — APPROVED** [review]
Just went through `text input`, `textarea`, and `select` in more detail. I didn't catch anything, so good to go from my perspective 👍

**Review by cveigt — APPROVED** [review]

**Pull request merged**
