### PR TITLE
Badge component - Add font weight declaration

### PR DESCRIPTION
**Pull request by didoo**
### :pushpin: Summary

Following this comment by @heatherlarsen https://github.com/hashicorp/design-system/pull/425#discussion_r914230335 I've realized we never explicitly set the `font-weight` property for the text in the `Badge` component. This has two problems: 1) it inherits from the container, as Heather noticed, and 2) it was using the wrong weight, it should be "medium".

### :hammer_and_wrench: Detailed description

In this PR I have:
- added font-weight “medium” to the text in the `Badge` component

***

### 👀 How to review

👉 Review commit-by-commit or by files changed

Reviewer's checklist:

- [ ] +1 Percy if applicable
- [ ] Confirm that PR has a changelog update via [Changesets](https://github.com/changesets/changesets) if needed

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

### CODE REVIEW

**Review by alex-ju — APPROVED** [review]
Makes sense! I'm not sure about the value of [redefining this property for the required badge](https://github.com/hashicorp/design-system/pull/425/files#diff-579dd1c81d1e3941513eba1ef2417d870f32bbc99683c737d8e48e9240c21414R9) in this case.

**Comment by didoo** [comment]
> Makes sense! I'm not sure about the value of [redefining this property for the required badge](https://github.com/hashicorp/design-system/pull/425/files#diff-579dd1c81d1e3941513eba1ef2417d870f32bbc99683c737d8e48e9240c21414R9) in this case.

Yes, we shouldn't in that case.

**Review by heatherlarsen — CHANGES_REQUESTED** [review]
This change also needs to be made for `BadgeCount`

**Review by heatherlarsen — APPROVED** [review]
lgtm! thanks @didoo 🙂

**Pull request merged**
