### PR TITLE
Shw Grid - Convert components to gts (HDS-3833)

### PR DESCRIPTION
**Pull request by KristinLBradley**
### :pushpin: Summary

If merged, this PR will convert the ShwGrid Showcase components to GTS format.

### :link: External links

* Jira ticket: [HDS-3833](https://hashicorp.atlassian.net/browse/HDS-3833)

***

### 👀 Component checklist

- [x] Percy was checked for any visual regression
- ~~[ ] A changelog entry was added via [Changesets](https://github.com/changesets/changesets) if needed (see [templates here](https://hashicorp.atlassian.net/wiki/spaces/HDS/pages/3243114706/Changelog+authoring+best+practices#Templates))~~

:speech_balloon: Please consider using [conventional comments](https://conventionalcomments.org/) when reviewing this PR.

[HDS-3833]: https://hashicorp.atlassian.net/browse/HDS-3833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by aklkv — APPROVED** [review]

**Review by didoo — COMMENTED** [review]
left a couple of suggestions

**Comment by didoo** [comment]
@KristinLBradley forgot to mention: you have also to update the import in the `template-registry.ts` file to include `index` in the file name, or `yarn run lint:hbs` would fail; see how it's done for example here:
https://github.com/hashicorp/design-system/pull/2426/commits/6c5f08069479abadcdf1ea31be8cf6d22ecfbdcc

**Comment by KristinLBradley** [comment]
> @KristinLBradley forgot to mention: you have also to update the import in the `template-registry.ts` file to include `index` in the file name, or `yarn run lint:hbs` would fail; see how it's done for example here: [6c5f080](https://github.com/hashicorp/design-system/commit/6c5f08069479abadcdf1ea31be8cf6d22ecfbdcc)

Added & pushed up, thanks. I tried running the linter though and wasn't seeing any errors?

**Review by didoo — APPROVED** [review]
👍

**Pull request merged**
